### ISSUE TITLE
Skip line comment doesn't work with version 7.6.4

### ISSUE THREAD

**Issue by CharAct3** [klen/pylama#133] opened 2018-10-10 03:44 UTC
I'm using `# pylama:skip=1` to skip code checking.
But it doesn't work when I upgrade to version 7.6.4.

```
src/config.py:1:1: E800: Found commented out code: # pylama: skip=1 [eradicate]
```

**Comment by aleufroy** [comment] 2018-10-31 13:05
I faced the same problem with 
```
[pylama:myfile.py]
skip = 1
```

It seems that it was caused by https://github.com/klen/pylama/commit/29f93e905196d76cb3f87e4c5f7d2852cbdfa89b

Maybe the [documentation](https://pylama.readthedocs.io/en/latest/#set-options-for-file-group-of-files) should reflects this change.

**Comment by xNinjaKittyx** [comment] 2019-09-25 19:23
Still same problem in 7.7.1
```
# pylama:skip=1
import os
```

```
★  pylama file.py                                       
file.py:3: [W] W0611 'os' imported but unused [pyflakes]
```

As a workaround, since its all warnings, I've been using `# pylama:ignore=W`

**Comment by klen** [comment] 2021-11-27 12:17
Thank you for the report. The issue has been fixed in pylama 8+

**Closed by klen** 2021-11-27 12:17 UTC
